version: 1.0.{build}-{branch}

environment:
  github_release_version: 1.0.$(APPVEYOR_BUILD_NUMBER)
  
branches:
  only:
    - master
    - release

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

shallow_clone: true

services:
  - mssql2014

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: FMStudio.sln
  verbosity: normal

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: FMStudio.App\bin\package
    name: FMStudio-portable

  - path: FMStudio.App\bin\installer\*

deploy:
    # Pre-release portable
  - provider: GitHub
    tag: preview
    artifact: /.FMStudio-$(github_release_version)-preview-portable\.zip/
    draft: false
    release: preview
    description: 'Preview release'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN

    # Pre-release installer
  - provider: GitHub
    tag: preview
    artifact: /./installer/*/
    draft: false
    release: preview
    description: 'Preview release'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN
      
    # Stable release portable
  - provider: GitHub
    tag: stable
    artifact: /.FMStudio-$(github_release_version)-preview-portable\.zip/
    draft: false
    release: stable
    description: 'Stable release'
    prerelease: false
    on:
      branch: release
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN

    # Stable release installer
  - provider: GitHub
    tag: stable
    artifact: /./installer/*/
    draft: false
    release: stable
    description: 'Stable release'
    prerelease: false
    on:
      branch: release
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN