version: 1.0.{build}-{branch}

branches:
  only:
    - master
    - appveyor

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

shallow_clone: true

services:
  - mssql2014

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: FMStudio.sln
  verbosity: normal

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: FMStudio.App\bin\package
  - path: FMStudio.App\bin\installer\*

deploy:
    # Portable
  - provider: GitHub
    tag: 'dev'
    artifact: /.package\.zip/
    draft: false
    release: 'portable-dev'
    description: 'Portable executable - dev branch'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN

    # Installer
  - provider: GitHub
    tag: 'dev'
    artifact: /./installer/*/
    draft: false
    release: 'installer-dev'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN