version: 1.0.{build}-{branch}

environment:
  version: 1.0.{build}
  
branches:
  only:
    - master
    - appveyor

os: Windows Server 2012

init:
  - git config --global core.autocrlf input

shallow_clone: true

services:
  - mssql2014

platform: Any CPU

configuration: Release

build:
  parallel: true
  project: FMStudio.sln
  verbosity: normal

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: FMStudio.App\bin\package
    name: portable

  - path: FMStudio.App\bin\installer\*

deploy:
    # Portable pre-release
  - provider: GitHub
    tag: $(version)
    artifact: /.portable\.zip/
    draft: true
    release: $(appveyor_build_version)
    description: 'Pre-release'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN

    # Installer pre-release
  - provider: GitHub
    tag: $(version)
    artifact: /./installer/*/
    draft: true
    release: $(appveyor_build_version)
    description: 'Pre-release'
    prerelease: true
    on:
      branch: master
    auth_token:
      secure: CGwvwmQSDLr9PoSwKckZc7FlGL3TGhhdbPVGcWiVSLLofpEJU9UintF4j9lfEQXN